name: Deploy to production

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  deploy:
      name: deploy
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Set up Node
          uses: actions/setup-node@v3

        - name: Install dependencies
          run: npm install

        - name: Build
          run: npm run build

        - name: Set up GitHub Pages
          uses: actions/configure-pages@v3

        - name: Upload artifact to GitHub Pages
          uses: actions/upload-pages-artifact@v1
          with:
            path: "./dist"

        - name: Deploy to GitHub Pages
          uses: actions/deploy-pages@v2
